// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.29.3
// source: drones-api/api/v1/model/drones.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DroneStatus int32

const (
	DroneStatus_DRONE_STATUS_AVAILABLE   DroneStatus = 0
	DroneStatus_DRONE_STATUS_IN_MISSION  DroneStatus = 1
	DroneStatus_DRONE_STATUS_CHARGING    DroneStatus = 2
	DroneStatus_DRONE_STATUS_MAINTENANCE DroneStatus = 3
	DroneStatus_DRONE_STATUS_OFFLINE     DroneStatus = 4
)

// Enum value maps for DroneStatus.
var (
	DroneStatus_name = map[int32]string{
		0: "DRONE_STATUS_AVAILABLE",
		1: "DRONE_STATUS_IN_MISSION",
		2: "DRONE_STATUS_CHARGING",
		3: "DRONE_STATUS_MAINTENANCE",
		4: "DRONE_STATUS_OFFLINE",
	}
	DroneStatus_value = map[string]int32{
		"DRONE_STATUS_AVAILABLE":   0,
		"DRONE_STATUS_IN_MISSION":  1,
		"DRONE_STATUS_CHARGING":    2,
		"DRONE_STATUS_MAINTENANCE": 3,
		"DRONE_STATUS_OFFLINE":     4,
	}
)

func (x DroneStatus) Enum() *DroneStatus {
	p := new(DroneStatus)
	*p = x
	return p
}

func (x DroneStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DroneStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_drones_api_api_v1_model_drones_proto_enumTypes[0].Descriptor()
}

func (DroneStatus) Type() protoreflect.EnumType {
	return &file_drones_api_api_v1_model_drones_proto_enumTypes[0]
}

func (x DroneStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DroneStatus.Descriptor instead.
func (DroneStatus) EnumDescriptor() ([]byte, []int) {
	return file_drones_api_api_v1_model_drones_proto_rawDescGZIP(), []int{0}
}

type Drone struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint64      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name      string      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status    DroneStatus `protobuf:"varint,3,opt,name=status,proto3,enum=drones_api.api.v1.model.DroneStatus" json:"status,omitempty"`
	CreatedBy string      `protobuf:"bytes,4,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
}

func (x *Drone) Reset() {
	*x = Drone{}
	if protoimpl.UnsafeEnabled {
		mi := &file_drones_api_api_v1_model_drones_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Drone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Drone) ProtoMessage() {}

func (x *Drone) ProtoReflect() protoreflect.Message {
	mi := &file_drones_api_api_v1_model_drones_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Drone.ProtoReflect.Descriptor instead.
func (*Drone) Descriptor() ([]byte, []int) {
	return file_drones_api_api_v1_model_drones_proto_rawDescGZIP(), []int{0}
}

func (x *Drone) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Drone) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Drone) GetStatus() DroneStatus {
	if x != nil {
		return x.Status
	}
	return DroneStatus_DRONE_STATUS_AVAILABLE
}

func (x *Drone) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

var File_drones_api_api_v1_model_drones_proto protoreflect.FileDescriptor

var file_drones_api_api_v1_model_drones_proto_rawDesc = []byte{
	0x0a, 0x24, 0x64, 0x72, 0x6f, 0x6e, 0x65, 0x73, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x64, 0x72, 0x6f, 0x6e, 0x65, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x17, 0x64, 0x72, 0x6f, 0x6e, 0x65, 0x73, 0x5f, 0x61,
	0x70, 0x69, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x22,
	0x88, 0x01, 0x0a, 0x05, 0x44, 0x72, 0x6f, 0x6e, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x3c, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x24, 0x2e,
	0x64, 0x72, 0x6f, 0x6e, 0x65, 0x73, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76,
	0x31, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x44, 0x72, 0x6f, 0x6e, 0x65, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x62, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x42, 0x79, 0x2a, 0x99, 0x01, 0x0a, 0x0b, 0x44,
	0x72, 0x6f, 0x6e, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1a, 0x0a, 0x16, 0x44, 0x52,
	0x4f, 0x4e, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x41, 0x56, 0x41, 0x49, 0x4c,
	0x41, 0x42, 0x4c, 0x45, 0x10, 0x00, 0x12, 0x1b, 0x0a, 0x17, 0x44, 0x52, 0x4f, 0x4e, 0x45, 0x5f,
	0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x49, 0x4e, 0x5f, 0x4d, 0x49, 0x53, 0x53, 0x49, 0x4f,
	0x4e, 0x10, 0x01, 0x12, 0x19, 0x0a, 0x15, 0x44, 0x52, 0x4f, 0x4e, 0x45, 0x5f, 0x53, 0x54, 0x41,
	0x54, 0x55, 0x53, 0x5f, 0x43, 0x48, 0x41, 0x52, 0x47, 0x49, 0x4e, 0x47, 0x10, 0x02, 0x12, 0x1c,
	0x0a, 0x18, 0x44, 0x52, 0x4f, 0x4e, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x4d,
	0x41, 0x49, 0x4e, 0x54, 0x45, 0x4e, 0x41, 0x4e, 0x43, 0x45, 0x10, 0x03, 0x12, 0x18, 0x0a, 0x14,
	0x44, 0x52, 0x4f, 0x4e, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x4f, 0x46, 0x46,
	0x4c, 0x49, 0x4e, 0x45, 0x10, 0x04, 0x42, 0x51, 0x5a, 0x4f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x56, 0x65, 0x6e, 0x65, 0x4c, 0x6f, 0x6f, 0x6f, 0x6f, 0x6c, 0x2f,
	0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2d, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2f,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x62, 0x2f, 0x64, 0x72, 0x6f, 0x6e,
	0x65, 0x73, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x3b, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_drones_api_api_v1_model_drones_proto_rawDescOnce sync.Once
	file_drones_api_api_v1_model_drones_proto_rawDescData = file_drones_api_api_v1_model_drones_proto_rawDesc
)

func file_drones_api_api_v1_model_drones_proto_rawDescGZIP() []byte {
	file_drones_api_api_v1_model_drones_proto_rawDescOnce.Do(func() {
		file_drones_api_api_v1_model_drones_proto_rawDescData = protoimpl.X.CompressGZIP(file_drones_api_api_v1_model_drones_proto_rawDescData)
	})
	return file_drones_api_api_v1_model_drones_proto_rawDescData
}

var file_drones_api_api_v1_model_drones_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_drones_api_api_v1_model_drones_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_drones_api_api_v1_model_drones_proto_goTypes = []any{
	(DroneStatus)(0), // 0: drones_api.api.v1.model.DroneStatus
	(*Drone)(nil),    // 1: drones_api.api.v1.model.Drone
}
var file_drones_api_api_v1_model_drones_proto_depIdxs = []int32{
	0, // 0: drones_api.api.v1.model.Drone.status:type_name -> drones_api.api.v1.model.DroneStatus
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_drones_api_api_v1_model_drones_proto_init() }
func file_drones_api_api_v1_model_drones_proto_init() {
	if File_drones_api_api_v1_model_drones_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_drones_api_api_v1_model_drones_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Drone); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_drones_api_api_v1_model_drones_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_drones_api_api_v1_model_drones_proto_goTypes,
		DependencyIndexes: file_drones_api_api_v1_model_drones_proto_depIdxs,
		EnumInfos:         file_drones_api_api_v1_model_drones_proto_enumTypes,
		MessageInfos:      file_drones_api_api_v1_model_drones_proto_msgTypes,
	}.Build()
	File_drones_api_api_v1_model_drones_proto = out.File
	file_drones_api_api_v1_model_drones_proto_rawDesc = nil
	file_drones_api_api_v1_model_drones_proto_goTypes = nil
	file_drones_api_api_v1_model_drones_proto_depIdxs = nil
}
